apiVersion: v2
name: hafnium-backend
description: Helm chart for Hafnium Backend Services
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies: []

keywords:
  - hafnium
  - compliance
  - aml
  - kyc
  - transaction-monitoring

home: https://github.com/hafnium/hafnium

maintainers:
  - name: Hafnium Team
    email: team@hafnium.dev
