apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hafnium-system

resources:
  - namespace.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: hafnium
      app.kubernetes.io/managed-by: kustomize
